<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150125144615 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_mate (persistence_object_identifier VARCHAR(40) NOT NULL, innermostself VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_1E84EE1741B3E602 (innermostself), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE1741B3E602 FOREIGN KEY (innermostself) REFERENCES t3dd_backend_domain_model_mate (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE1747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_mate");
	}
}