<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150330215710 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress DROP FOREIGN KEY FK_4A06980362A8A7A7");
		$this->addSql("DROP INDEX IDX_4A06980362A8A7A7 ON t3dd_backend_domain_model_registration_billingaddress");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress DROP registration");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_registration ADD billingaddress VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_registration ADD CONSTRAINT FK_773F6465B1A7AB52 FOREIGN KEY (billingaddress) REFERENCES t3dd_backend_domain_model_registration_billingaddress (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_773F6465B1A7AB52 ON t3dd_backend_domain_model_registration_registration (billingaddress)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress ADD registration VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress ADD CONSTRAINT FK_4A06980362A8A7A7 FOREIGN KEY (registration) REFERENCES t3dd_backend_domain_model_registration_registration (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_4A06980362A8A7A7 ON t3dd_backend_domain_model_registration_billingaddress (registration)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_registration DROP FOREIGN KEY FK_773F6465B1A7AB52");
		$this->addSql("DROP INDEX UNIQ_773F6465B1A7AB52 ON t3dd_backend_domain_model_registration_registration");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_registration DROP billingaddress");
	}
}