<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150205220722 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant CHANGE foottype foodtype VARCHAR(255) NOT NULL, CHANGE footwishes foodwishes VARCHAR(255) NOT NULL, CHANGE noob newcomer TINYINT(1) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant CHANGE foodtype foottype VARCHAR(255) NOT NULL, CHANGE foodwishes footwishes VARCHAR(255) NOT NULL, CHANGE newcomer noob TINYINT(1) NOT NULL");
	}
}