<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150329161243 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant CHANGE rate rate ENUM('noassoc', 'assoc', 'student', 'speaker', 'core', 'helper', 'sponsornonassoc', 'sponsornassoc', 'voucher'), CHANGE roomsize roomsize ENUM('0', '2', '3', '4'), CHANGE foodtype foodtype ENUM('default', 'vegetarian', 'vegan'), CHANGE tshirtsize tshirtsize ENUM('xs', 's', 'm', 'l', 'xl', 'xxl', '3xl', '4xl'), CHANGE tshirttype tshirttype ENUM('default', 'girlie')");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room CHANGE fraction fraction INT NOT NULL, CHANGE bookingstate bookingstate ENUM('pending', 'waiting', 'booked')");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket CHANGE fraction fraction INT NOT NULL, CHANGE bookingstate bookingstate ENUM('pending', 'waiting', 'booked')");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant CHANGE rate rate VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE roomsize roomsize VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE foodtype foodtype VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE tshirtsize tshirtsize VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci, CHANGE tshirttype tshirttype VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room CHANGE fraction fraction DOUBLE PRECISION NOT NULL, CHANGE bookingstate bookingstate VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket CHANGE fraction fraction DOUBLE PRECISION NOT NULL, CHANGE bookingstate bookingstate VARCHAR(255) DEFAULT NULL COLLATE utf8_unicode_ci");
	}
}