<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150302094334 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_account (persistence_object_identifier VARCHAR(40) NOT NULL, payload VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_539CC9C422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_value (persistence_object_identifier VARCHAR(40) NOT NULL, payload VARCHAR(40) DEFAULT NULL, UNIQUE INDEX UNIQ_23D03D79422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_account ADD CONSTRAINT FK_539CC9C422C6A15 FOREIGN KEY (payload) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_account ADD CONSTRAINT FK_539CC9C47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_value ADD CONSTRAINT FK_23D03D79422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_value (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_value ADD CONSTRAINT FK_23D03D7947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_account");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_value");
	}
}