<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150605102832 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("INSERT INTO t3dd_backend_domain_model_participant SELECT persistence_object_identifier, account, name, email, companyname, country, rate, roomsize, '' as roommates, foodtype, foodwishes, tshirtsize, tshirttype, newcomer, yearexpertise, 0 as completed, '2016-04-08 00:00:00' as lastemailsent from t3dd_backend_domain_model_registration_participant");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("TRUNCATE TABLE t3dd_backend_domain_model_participant");
	}
}