<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150306120948 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$values = array(
			'theme' => array(
				'c5b77a85-9aeb-4b79-9536-d1a4186280b6' => 'Design',
				'f1ce4225-28e1-4243-b91c-9eb31d9de11a' => 'Architecture',
				'fb9bb7f0-44d4-4e77-94b4-88c87fd673f5' => 'Other'),
		);

		foreach ($values as $category => $selections) {
			foreach ($selections as $persistenceObjectIdentifier => $selection) {
				$query = "INSERT INTO t3dd_backend_domain_model_value (persistence_object_identifier, title, type) VALUES ('" . $persistenceObjectIdentifier . "','" . $selection . "','" . $category . "');";
				$this->addSql($query);
			}
		}
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
	}
}