<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150402221030 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD isregistrant TINYINT(1) NOT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD ticket VARCHAR(40) DEFAULT NULL, ADD room VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD CONSTRAINT FK_9A71E04C97A0ADA3 FOREIGN KEY (ticket) REFERENCES t3dd_backend_domain_model_registration_ticket (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD CONSTRAINT FK_9A71E04C729F519B FOREIGN KEY (room) REFERENCES t3dd_backend_domain_model_registration_room (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_9A71E04C97A0ADA3 ON t3dd_backend_domain_model_registration_participant (ticket)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_9A71E04C729F519B ON t3dd_backend_domain_model_registration_participant (room)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room DROP FOREIGN KEY FK_80EBF6BAD79F6B11");
		$this->addSql("DROP INDEX IDX_80EBF6BAD79F6B11 ON t3dd_backend_domain_model_registration_room");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room DROP participant");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket DROP FOREIGN KEY FK_538D7C7FD79F6B11");
		$this->addSql("DROP INDEX IDX_538D7C7FD79F6B11 ON t3dd_backend_domain_model_registration_ticket");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
	}
}