<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150617001919 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_vote DROP FOREIGN KEY FK_2A2F9DD5D044D5D4");
		$this->addSql("DROP INDEX IDX_2A2F9DD5D044D5D4 ON t3dd_backend_domain_model_vote");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_vote CHANGE session session VARCHAR(255) NOT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE t3dd_backend_domain_model_vote CHANGE session session VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_vote ADD CONSTRAINT FK_2A2F9DD5D044D5D4 FOREIGN KEY (session) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_2A2F9DD5D044D5D4 ON t3dd_backend_domain_model_vote (session)");
	}
}