<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150302200751 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_session_themes_join (backend_session VARCHAR(40) NOT NULL, backend_value VARCHAR(40) NOT NULL, INDEX IDX_CB22E925E84CD28D (backend_session), INDEX IDX_CB22E925B8FC0DD1 (backend_value), PRIMARY KEY(backend_session, backend_value)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session_themes_join ADD CONSTRAINT FK_CB22E925E84CD28D FOREIGN KEY (backend_session) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session_themes_join ADD CONSTRAINT FK_CB22E925B8FC0DD1 FOREIGN KEY (backend_value) REFERENCES t3dd_backend_domain_model_value (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session DROP FOREIGN KEY FK_20A5F4E79775E708");
		$this->addSql("DROP INDEX IDX_20A5F4E79775E708 ON t3dd_backend_domain_model_session");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session DROP theme");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE t3dd_backend_domain_model_session_themes_join");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session ADD theme VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session ADD CONSTRAINT FK_20A5F4E79775E708 FOREIGN KEY (theme) REFERENCES t3dd_backend_domain_model_value (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_20A5F4E79775E708 ON t3dd_backend_domain_model_session (theme)");
	}
}