<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150408034610 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket DROP participant");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_mate DROP FOREIGN KEY FK_25E2DFD17D3656A4");
		$this->addSql("DROP INDEX IDX_25E2DFD17D3656A4 ON t3dd_backend_domain_model_registration_mate");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_mate DROP account, ADD participant VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_mate ADD CONSTRAINT FK_25E2DFD1D79F6B11 FOREIGN KEY (participant) REFERENCES t3dd_backend_domain_model_registration_participant (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_25E2DFD1D79F6B11 ON t3dd_backend_domain_model_registration_mate (participant)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		// FOO
	}
}