<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150320184559 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_account DROP FOREIGN KEY FK_539CC9C47A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate DROP FOREIGN KEY FK_1E84EE1747A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant DROP FOREIGN KEY FK_CBC263B847A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session DROP FOREIGN KEY FK_A84B4FEC47A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker DROP FOREIGN KEY FK_38A415947A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_value DROP FOREIGN KEY FK_23D03D7947A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_vote DROP FOREIGN KEY FK_9302138347A46B0A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate DROP FOREIGN KEY FK_1E84EE17422C6A15");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant_roommates_join DROP FOREIGN KEY FK_821604EA5676F6D7");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant DROP FOREIGN KEY FK_CBC263B8422C6A15");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker DROP FOREIGN KEY FK_38A4159422C6A15");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant_roommates_join DROP FOREIGN KEY FK_821604EA840E0F2A");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session_speakers_join DROP FOREIGN KEY FK_496127ED840E0F2A");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_billingaddress (persistence_object_identifier VARCHAR(40) NOT NULL, registration VARCHAR(40) DEFAULT NULL, companyname VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, zip VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, INDEX IDX_4A06980362A8A7A7 (registration), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_mate (persistence_object_identifier VARCHAR(40) NOT NULL, account VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_25E2DFD17D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_room (persistence_object_identifier VARCHAR(40) NOT NULL, participant VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, fraction DOUBLE PRECISION NOT NULL, bookingstate ENUM('pending', 'waiting', 'booked'), quotaapplies TINYINT(1) NOT NULL, INDEX IDX_80EBF6BAD79F6B11 (participant), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_ticket (persistence_object_identifier VARCHAR(40) NOT NULL, participant VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, fraction DOUBLE PRECISION NOT NULL, bookingstate ENUM('pending', 'waiting', 'booked'), quotaapplies TINYINT(1) NOT NULL, INDEX IDX_538D7C7FD79F6B11 (participant), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_participant (persistence_object_identifier VARCHAR(40) NOT NULL, registration VARCHAR(40) DEFAULT NULL, account VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, company VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, rate ENUM('noassoc', 'assoc', 'css', 'helper', 'sponsornonassoc', 'sponsornassoc', 'voucher'), roomsize ENUM('0', '2', '3', '4'), roomgroup VARCHAR(255) NOT NULL, foodtype ENUM('default', 'vegetarian', 'vegan'), foodwishes LONGTEXT NOT NULL, tshirtsize ENUM('xs', 's', 'm', 'l', 'xl', 'xxl', '3xl', '4xl'), tshirttype ENUM('default', 'girlie'), newcomer TINYINT(1) NOT NULL, yearexpertise INT NOT NULL, INDEX IDX_9A71E04C62A8A7A7 (registration), INDEX IDX_9A71E04C7D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join (backend_registration_participant VARCHAR(40) NOT NULL, backend_registration_mate VARCHAR(40) NOT NULL, INDEX IDX_8137AF3E144EDE90 (backend_registration_participant), INDEX IDX_8137AF3E71A15FE7 (backend_registration_mate), PRIMARY KEY(backend_registration_participant, backend_registration_mate)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_registration_registration (persistence_object_identifier VARCHAR(40) NOT NULL, account VARCHAR(40) DEFAULT NULL, date DATETIME NOT NULL, participantcount INT NOT NULL, notes LONGTEXT NOT NULL, completed TINYINT(1) NOT NULL, INDEX IDX_773F64657D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress ADD CONSTRAINT FK_4A06980362A8A7A7 FOREIGN KEY (registration) REFERENCES t3dd_backend_domain_model_registration_registration (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_mate ADD CONSTRAINT FK_25E2DFD17D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room ADD CONSTRAINT FK_80EBF6BAD79F6B11 FOREIGN KEY (participant) REFERENCES t3dd_backend_domain_model_registration_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket ADD CONSTRAINT FK_538D7C7FD79F6B11 FOREIGN KEY (participant) REFERENCES t3dd_backend_domain_model_registration_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD CONSTRAINT FK_9A71E04C62A8A7A7 FOREIGN KEY (registration) REFERENCES t3dd_backend_domain_model_registration_registration (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant ADD CONSTRAINT FK_9A71E04C7D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join ADD CONSTRAINT FK_8137AF3E144EDE90 FOREIGN KEY (backend_registration_participant) REFERENCES t3dd_backend_domain_model_registration_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join ADD CONSTRAINT FK_8137AF3E71A15FE7 FOREIGN KEY (backend_registration_mate) REFERENCES t3dd_backend_domain_model_registration_mate (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_registration ADD CONSTRAINT FK_773F64657D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("DROP TABLE netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_account");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_mate");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_participant");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_session");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_speaker");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_value");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_datatransfer_vote");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_mate");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_participant");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_participant_roommates_join");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_session_speakers_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join DROP FOREIGN KEY FK_8137AF3E71A15FE7");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_room DROP FOREIGN KEY FK_80EBF6BAD79F6B11");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_ticket DROP FOREIGN KEY FK_538D7C7FD79F6B11");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join DROP FOREIGN KEY FK_8137AF3E144EDE90");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_billingaddress DROP FOREIGN KEY FK_4A06980362A8A7A7");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_registration_participant DROP FOREIGN KEY FK_9A71E04C62A8A7A7");
		$this->addSql("CREATE TABLE netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, dtype VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_account (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_539CC9C422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_mate (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_1E84EE17422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_participant (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, resource VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_CBC263B8422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_session (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_A84B4FEC422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_speaker (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_38A4159422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_value (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_23D03D79422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_datatransfer_vote (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, payload VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, UNIQUE INDEX UNIQ_93021383422C6A15 (payload), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_mate (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, username VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, email VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_participant (persistence_object_identifier VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, account VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci, date DATETIME NOT NULL, name VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, company VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, street VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, zip VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, city VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, country VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, foodtype VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, foodwishes VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, tshirtsize VARCHAR(255) NOT NULL COLLATE utf8_unicode_ci, newcomer TINYINT(1) NOT NULL, room TINYINT(1) NOT NULL, roomsize INT NOT NULL, UNIQUE INDEX UNIQ_F65620387D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_participant_roommates_join (backend_participant VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, backend_mate VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_821604EA840E0F2A (backend_participant), INDEX IDX_821604EA5676F6D7 (backend_mate), PRIMARY KEY(backend_participant, backend_mate)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE t3dd_backend_domain_model_session_speakers_join (backend_session VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, backend_participant VARCHAR(40) NOT NULL COLLATE utf8_unicode_ci, INDEX IDX_496127EDE84CD28D (backend_session), INDEX IDX_496127ED840E0F2A (backend_participant), PRIMARY KEY(backend_session, backend_participant)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_account ADD CONSTRAINT FK_539CC9C422C6A15 FOREIGN KEY (payload) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_account ADD CONSTRAINT FK_539CC9C47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE17422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_mate (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE1747A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant ADD CONSTRAINT FK_CBC263B8422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant ADD CONSTRAINT FK_CBC263B847A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session ADD CONSTRAINT FK_A84B4FEC422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session ADD CONSTRAINT FK_A84B4FEC47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker ADD CONSTRAINT FK_38A4159422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker ADD CONSTRAINT FK_38A415947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_value ADD CONSTRAINT FK_23D03D79422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_value (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_value ADD CONSTRAINT FK_23D03D7947A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_vote ADD CONSTRAINT FK_93021383422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_vote (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_vote ADD CONSTRAINT FK_9302138347A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES netlogix_crud_domain_model_datatransfer_abstractdatatrans_3c9fe (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant ADD CONSTRAINT FK_F65620387D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant_roommates_join ADD CONSTRAINT FK_821604EA5676F6D7 FOREIGN KEY (backend_mate) REFERENCES t3dd_backend_domain_model_mate (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant_roommates_join ADD CONSTRAINT FK_821604EA840E0F2A FOREIGN KEY (backend_participant) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session_speakers_join ADD CONSTRAINT FK_496127ED840E0F2A FOREIGN KEY (backend_participant) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_session_speakers_join ADD CONSTRAINT FK_496127EDE84CD28D FOREIGN KEY (backend_session) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_billingaddress");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_mate");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_room");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_ticket");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_participant");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_par_d628a_roommates_join");
		$this->addSql("DROP TABLE t3dd_backend_domain_model_registration_registration");
	}
}