<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150202212205 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant ADD account VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant ADD CONSTRAINT FK_F65620387D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_F65620387D3656A4 ON t3dd_backend_domain_model_participant (account)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant DROP FOREIGN KEY FK_F65620387D3656A4");
		$this->addSql("DROP INDEX UNIQ_F65620387D3656A4 ON t3dd_backend_domain_model_participant");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_participant DROP account");
	}
}