<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150216215347 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate DROP FOREIGN KEY FK_1E84EE1741B3E602");
		$this->addSql("DROP INDEX UNIQ_1E84EE1741B3E602 ON t3dd_backend_domain_model_datatransfer_mate");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate CHANGE innermostself payload VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE17422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_mate (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_1E84EE17422C6A15 ON t3dd_backend_domain_model_datatransfer_mate (payload)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant DROP FOREIGN KEY FK_CBC263B841B3E602");
		$this->addSql("DROP INDEX UNIQ_CBC263B841B3E602 ON t3dd_backend_domain_model_datatransfer_participant");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant CHANGE innermostself payload VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant ADD CONSTRAINT FK_CBC263B8422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_CBC263B8422C6A15 ON t3dd_backend_domain_model_datatransfer_participant (payload)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session DROP FOREIGN KEY FK_A84B4FEC41B3E602");
		$this->addSql("DROP INDEX UNIQ_A84B4FEC41B3E602 ON t3dd_backend_domain_model_datatransfer_session");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session CHANGE innermostself payload VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session ADD CONSTRAINT FK_A84B4FEC422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_A84B4FEC422C6A15 ON t3dd_backend_domain_model_datatransfer_session (payload)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker DROP FOREIGN KEY FK_38A415941B3E602");
		$this->addSql("DROP INDEX UNIQ_38A415941B3E602 ON t3dd_backend_domain_model_datatransfer_speaker");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker CHANGE innermostself payload VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker ADD CONSTRAINT FK_38A4159422C6A15 FOREIGN KEY (payload) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_38A4159422C6A15 ON t3dd_backend_domain_model_datatransfer_speaker (payload)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate DROP FOREIGN KEY FK_1E84EE17422C6A15");
		$this->addSql("DROP INDEX UNIQ_1E84EE17422C6A15 ON t3dd_backend_domain_model_datatransfer_mate");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate CHANGE payload innermostself VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_mate ADD CONSTRAINT FK_1E84EE1741B3E602 FOREIGN KEY (innermostself) REFERENCES t3dd_backend_domain_model_mate (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_1E84EE1741B3E602 ON t3dd_backend_domain_model_datatransfer_mate (innermostself)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant DROP FOREIGN KEY FK_CBC263B8422C6A15");
		$this->addSql("DROP INDEX UNIQ_CBC263B8422C6A15 ON t3dd_backend_domain_model_datatransfer_participant");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant CHANGE payload innermostself VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_participant ADD CONSTRAINT FK_CBC263B841B3E602 FOREIGN KEY (innermostself) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_CBC263B841B3E602 ON t3dd_backend_domain_model_datatransfer_participant (innermostself)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session DROP FOREIGN KEY FK_A84B4FEC422C6A15");
		$this->addSql("DROP INDEX UNIQ_A84B4FEC422C6A15 ON t3dd_backend_domain_model_datatransfer_session");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session CHANGE payload innermostself VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_session ADD CONSTRAINT FK_A84B4FEC41B3E602 FOREIGN KEY (innermostself) REFERENCES t3dd_backend_domain_model_session (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_A84B4FEC41B3E602 ON t3dd_backend_domain_model_datatransfer_session (innermostself)");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker DROP FOREIGN KEY FK_38A4159422C6A15");
		$this->addSql("DROP INDEX UNIQ_38A4159422C6A15 ON t3dd_backend_domain_model_datatransfer_speaker");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker CHANGE payload innermostself VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE t3dd_backend_domain_model_datatransfer_speaker ADD CONSTRAINT FK_38A415941B3E602 FOREIGN KEY (innermostself) REFERENCES t3dd_backend_domain_model_participant (persistence_object_identifier)");
		$this->addSql("CREATE UNIQUE INDEX UNIQ_38A415941B3E602 ON t3dd_backend_domain_model_datatransfer_speaker (innermostself)");
	}
}